### ISSUE TITLE
Fails to find using InstrumentationDriver instance on API >= 18

### ISSUE THREAD

**Issue by 0x1mason** [appium/droiddriver#6]
API 21 tested.

```java
        DroidDriver dd = DroidDrivers.newInstrumentationDriver(this.getInstrumentation());
        DroidDrivers.init(dd);
        ActivityUtils.setRunningActivitySupplier(new Supplier<Activity>() {
            @Override
            public Activity get() {
                return getActivity();
            }
        });
        UiElement e = dd.find(By.contentDescription("foo"));
```

```
Test running started
com.google.android.droiddriver.exceptions.DroidDriverException: com.google.android.droiddriver.exceptions.DroidDriverException: Reflective access to private final java.util.ArrayList android.view.WindowManagerGlobal.mViews on android.view.WindowManagerGlobal@3caf716 failed.
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.findRootView(InstrumentationDriver.java:92)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.newRootElement(InstrumentationDriver.java:53)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.newRootElement(InstrumentationDriver.java:35)
at com.google.android.droiddriver.base.BaseDroidDriver.refreshUiElementTree(BaseDroidDriver.java:110)
at com.google.android.droiddriver.base.BaseDroidDriver.getRootElement(BaseDroidDriver.java:103)
at com.google.android.droiddriver.base.BaseDroidDriver.find(BaseDroidDriver.java:40)
at com.saucelabs.myapplication.ExampleTest.test(ExampleTest.java:54)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
Caused by: com.google.android.droiddriver.exceptions.DroidDriverException: Reflective access to private final java.util.ArrayList android.view.WindowManagerGlobal.mViews on android.view.WindowManagerGlobal@3caf716 failed.
at com.google.android.droiddriver.instrumentation.RootFinder.getRootViews(RootFinder.java:81)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver$FindRootViewRunnable.run(InstrumentationDriver.java:68)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:1855)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to android.view.View[]
at com.google.android.droiddriver.instrumentation.RootFinder.getRootViews(RootFinder.java:78)
... 12 more
```

**Comment by bootstraponline** [comment]
Latest version still crashing however the error message is different.

```

Running tests
Test running started
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.google.android.droiddriver.util.ActivityUtils$Supplier.get()' on a null object reference
at com.google.android.droiddriver.util.ActivityUtils.getRunningActivity(ActivityUtils.java:56)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.waitForRunningActivity(InstrumentationDriver.java:103)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.findRootView(InstrumentationDriver.java:90)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.newRootElement(InstrumentationDriver.java:55)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.newRootElement(InstrumentationDriver.java:37)
at com.google.android.droiddriver.base.BaseDroidDriver.refreshUiElementTree(BaseDroidDriver.java:112)
at com.google.android.droiddriver.base.DefaultPoller.pollFor(DefaultPoller.java:69)
at com.google.android.droiddriver.base.DefaultPoller.pollFor(DefaultPoller.java:60)
at com.google.android.droiddriver.base.BaseDroidDriver.on(BaseDroidDriver.java:69)
at com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest.find(ChangeTextBehaviorTest.java:84)
at com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest.id(ChangeTextBehaviorTest.java:88)
at com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest.testChangeText_newActivity(ChangeTextBehaviorTest.java:112)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.google.android.droiddriver.helpers.BaseDroidDriverTest.runTest(BaseDroidDriverTest.java:230)
at com.google.android.droiddriver.helpers.BaseDroidDriverTest.runBare(BaseDroidDriverTest.java:171)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at junit.framework.TestResult.runProtected(TestResult.java:133)
at android.support.test.internal.runner.junit3.DelegatingTestResult.runProtected(DelegatingTestResult.java:90)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:49)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:63)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)


java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.google.android.droiddriver.util.ActivityUtils$Supplier.get()' on a null object reference
at com.google.android.droiddriver.util.ActivityUtils.getRunningActivity(ActivityUtils.java:56)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.waitForRunningActivity(InstrumentationDriver.java:103)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.findRootView(InstrumentationDriver.java:90)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.newRootElement(InstrumentationDriver.java:55)
at com.google.android.droiddriver.instrumentation.InstrumentationDriver.newRootElement(InstrumentationDriver.java:37)
at com.google.android.droiddriver.base.BaseDroidDriver.refreshUiElementTree(BaseDroidDriver.java:112)
at com.google.android.droiddriver.base.DefaultPoller.pollFor(DefaultPoller.java:69)
at com.google.android.droiddriver.base.DefaultPoller.pollFor(DefaultPoller.java:60)
at com.google.android.droiddriver.base.BaseDroidDriver.on(BaseDroidDriver.java:69)
at com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest.find(ChangeTextBehaviorTest.java:84)
at com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest.id(ChangeTextBehaviorTest.java:88)
at com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorTest.testChangeText_sameActivity(ChangeTextBehaviorTest.java:98)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.google.android.droiddriver.helpers.BaseDroidDriverTest.runTest(BaseDroidDriverTest.java:230)
at com.google.android.droiddriver.helpers.BaseDroidDriverTest.runBare(BaseDroidDriverTest.java:171)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at junit.framework.TestResult.runProtected(TestResult.java:133)
at android.support.test.internal.runner.junit3.DelegatingTestResult.runProtected(DelegatingTestResult.java:90)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:49)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:63)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

Finish
```

**Comment by 0x1mason** [comment]
@bootstraponline It's working for me now.

```java
    @Override
    protected void classSetUp() {
         DroidDrivers.init(DroidDrivers.newInstrumentationDriver(getInstrumentation()));
    }

    public void testChangeText_newActivity() {
        ActivityUtils.setRunningActivitySupplier(new ActivityUtils.Supplier<Activity>() {
            @Override
            public Activity get() {
                return getActivity();
            }
        });
        DroidDrivers.get().refreshUiElementTree();
        UiElement e = id(R.id.editTextUserInput);
    }

```

**Comment by bootstraponline** [comment]
@0x1mason Use [this testcase](https://github.com/appium/droiddriver_examples/blob/eb4bdde93fd7ec7db622b1997b63320389c792bf/espresso_sample/espresso/BasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/ChangeTextBehaviorTest.java#L74) and change the driver to the instrumentation driver.

**Comment by bootstraponline** [comment]
> It's working for me now.

I'm using the espresso test runner so that's probably one difference between our setups.

**Comment by ddkjin** [comment]
ActivityUtils mentions that "InstrumentationDriver depends on this". I think we need to better surface this requirement, maybe in InstrumentationDriver itself.

**Comment by bootstraponline** [comment]
I think that's the problem. The code I'm using doesn't have: `ActivityUtils.setRunningActivitySupplier`

I agree this needs to be better documented. It'd be nice to raise a meaningful runtime exception if there's no supplier.

**Comment by bootstraponline** [comment]
https://android-review.googlesource.com/#/c/132420/1 will resolve this issue once merged.
